export const WS_FEED_CONNECTION_START: 'WS_FEED_CONNECTION_START' = 'WS_FEED_CONNECTION_START';
export const WS_FEED_CONNECTION_SUCCESS: 'WS_FEED_CONNECTION_SUCCESS' = 'WS_FEED_CONNECTION_SUCCESS';
export const WS_FEED_CONNECTION_ERROR: 'WS_FEED_CONNECTION_ERROR' = 'WS_FEED_CONNECTION_ERROR';
export const WS_FEED_CONNECTION_CLOSED: 'WS_FEED_CONNECTION_CLOSED' = 'WS_FEED_CONNECTION_CLOSED';
export const WS_FEED_GET_MESSAGE: 'WS_FEED_GET_MESSAGE' = 'WS_FEED_GET_MESSAGE';
export const WS_FEED_SEND_MESSAGE: 'WS_FEED_SEND_MESSAGE' = 'WS_FEED_SEND_MESSAGE';

export const WS_USER_FEED_CONNECTION_START: 'WS_USER_FEED_CONNECTION_START' = 'WS_USER_FEED_CONNECTION_START';
export const WS_USER_FEED_CONNECTION_SUCCESS: 'WS_USER_FEED_CONNECTION_SUCCESS' = 'WS_USER_FEED_CONNECTION_SUCCESS';
export const WS_USER_FEED_CONNECTION_ERROR: 'WS_USER_FEED_CONNECTION_ERROR' = 'WS_USER_FEED_CONNECTION_ERROR';
export const WS_USER_FEED_CONNECTION_CLOSED: 'WS_USER_FEED_CONNECTION_CLOSED' = 'WS_USER_FEED_CONNECTION_CLOSED';
export const WS_USER_FEED_GET_MESSAGE: 'WS_USER_FEED_GET_MESSAGE' = 'WS_USER_FEED_GET_MESSAGE';
export const WS_USER_FEED_SEND_MESSAGE: 'WS_USER_FEED_SEND_MESSAGE' = 'WS_USER_FEED_SEND_MESSAGE';
